/**
 * jscolor - JavaScript Color Picker
 *
 * @link    http://jscolor.com
 * @license For open source use: GPLv3
 *          For commercial use: JSColor Commercial License
 * @author  Jan Odvarko - East Desire
 * @version 2.3.2
 *
 * See usage examples at http://jscolor.com/examples/
 */
"use strict";
var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.checkStringArgs=function(a,b,c){if(null==a)throw new TypeError("The 'this' value for String.prototype."+c+" must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype."+c+" must not be a regular expression");return a+""};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.polyfill=function(a,b,c,d){if(b){c=$jscomp.global;a=a.split(".");for(d=0;d<a.length-1;d++){var f=a[d];f in c||(c[f]={});c=c[f]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})}};
$jscomp.polyfill("String.prototype.repeat",function(a){return a?a:function(a){var b=$jscomp.checkStringArgs(this,null,"repeat");if(0>a||1342177279<a)throw new RangeError("Invalid count value");a|=0;for(var d="";a;)if(a&1&&(d+=b),a>>>=1)b+=b;return d}},"es6","es3");
window.jscolor||(window.jscolor=function(){var a={initialized:!1,instances:[],triggerQueue:[],register:function(){document.addEventListener("DOMContentLoaded",a.init,!1);document.addEventListener("mousedown",a.onDocumentMouseDown,!1);document.addEventListener("keyup",a.onDocumentKeyUp,!1);window.addEventListener("resize",a.onWindowResize,!1)},init:function(){if(!a.initialized)for(a.pub.install(),a.initialized=!0;a.triggerQueue.length;){var b=a.triggerQueue.shift();a.triggerGlobal(b)}},installBySelector:function(b,
c){c=c?a.node(c):document;if(!c)throw Error("Missing root node");b=c.querySelectorAll(b);c=new RegExp("(^|\\s)("+a.pub.lookupClass+")(\\s*(\\{[^}]*\\})|\\s|$)","i");for(var d=0;d<b.length;d+=1)if(!(b[d].jscolor&&b[d].jscolor instanceof a.pub||void 0!==b[d].type&&"color"==b[d].type.toLowerCase()&&a.isColorAttrSupported)){var f,g;if(null!==(f=a.getDataAttr(b[d],"jscolor"))||b[d].className&&(g=b[d].className.match(c))){var h=b[d],k="";null!==f?k=f:g&&(console.warn('Installation using class name is DEPRECATED. Use data-jscolor="" attribute instead.'+
a.docsRef),g[4]&&(k=g[4]));f=null;if(k.trim())try{f=a.parseOptionsStr(k)}catch(l){console.warn(l+"\n"+k)}try{new a.pub(h,f)}catch(l){console.warn(l)}}}},parseOptionsStr:function(b){var c=null;try{c=JSON.parse(b)}catch(d){if(a.pub.looseJSON)try{c=(new Function("var opts = ("+b+'); return typeof opts === "object" ? opts : {};'))()}catch(f){throw Error("Could not evaluate jscolor options: "+f);}else throw Error("Could not parse jscolor options as JSON: "+d);}return c},getInstances:function(){for(var b=
[],c=0;c<a.instances.length;c+=1)a.instances[c]&&a.instances[c].targetElement&&b.push(a.instances[c]);return b},createEl:function(b){b=document.createElement(b);a.setData(b,"gui",!0);return b},node:function(b){if(!b)return null;if("string"===typeof b){var c=null;try{c=document.querySelector(b)}catch(d){return console.warn(d),null}c||console.warn("No element matches the selector: %s",b);return c}if(a.isNode(b))return b;console.warn("Invalid node of type %s: %s",typeof b,b);return null},isNode:function(a){return"object"===
typeof Node?a instanceof Node:a&&"object"===typeof a&&"number"===typeof a.nodeType&&"string"===typeof a.nodeName},nodeName:function(a){return a&&a.nodeName?a.nodeName.toLowerCase():!1},removeChildren:function(a){for(;a.firstChild;)a.removeChild(a.firstChild)},isTextInput:function(b){return b&&"input"===a.nodeName(b)&&"text"===b.type.toLowerCase()},isButton:function(b){if(!b)return!1;var c=a.nodeName(b);return"button"===c||"input"===c&&-1<["button","submit","reset"].indexOf(b.type.toLowerCase())},
isButtonEmpty:function(b){switch(a.nodeName(b)){case "input":return!b.value||""===b.value.trim();case "button":return""===b.textContent.trim()}return null},isPassiveEventSupported:function(){var a=!1;try{var c=Object.defineProperty({},"passive",{get:function(){a=!0}});window.addEventListener("testPassive",null,c);window.removeEventListener("testPassive",null,c)}catch(d){}return a}(),isColorAttrSupported:function(){var a=document.createElement("input");return a.setAttribute&&(a.setAttribute("type",
"color"),"color"==a.type.toLowerCase())?!0:!1}(),dataProp:"_data_jscolor",setData:function(){var b=arguments[0];if(3===arguments.length){b=b.hasOwnProperty(a.dataProp)?b[a.dataProp]:b[a.dataProp]={};var c=arguments[1];b[c]=arguments[2];return!0}if(2===arguments.length&&"object"===typeof arguments[1]){b=b.hasOwnProperty(a.dataProp)?b[a.dataProp]:b[a.dataProp]={};var d=arguments[1];for(c in d)d.hasOwnProperty(c)&&(b[c]=d[c]);return!0}throw Error("Invalid arguments");},removeData:function(){var b=arguments[0];
if(!b.hasOwnProperty(a.dataProp))return!0;for(var c=1;c<arguments.length;c+=1)delete b[a.dataProp][arguments[c]];return!0},getData:function(b,c,d){if(!b.hasOwnProperty(a.dataProp))if(void 0!==d)b[a.dataProp]={};else return;b=b[a.dataProp];b.hasOwnProperty(c)||void 0===d||(b[c]=d);return b[c]},getDataAttr:function(a,c){return a.getAttribute("data-"+c)},_attachedGroupEvents:{},attachGroupEvent:function(b,c,d,f){a._attachedGroupEvents.hasOwnProperty(b)||(a._attachedGroupEvents[b]=[]);a._attachedGroupEvents[b].push([c,
d,f]);c.addEventListener(d,f,!1)},detachGroupEvents:function(b){if(a._attachedGroupEvents.hasOwnProperty(b)){for(var c=0;c<a._attachedGroupEvents[b].length;c+=1){var d=a._attachedGroupEvents[b][c];d[0].removeEventListener(d[1],d[2],!1)}delete a._attachedGroupEvents[b]}},preventDefault:function(a){a.preventDefault&&a.preventDefault();a.returnValue=!1},captureTarget:function(b){b.setCapture&&(a._capturedTarget=b,a._capturedTarget.setCapture())},releaseTarget:function(){a._capturedTarget&&(a._capturedTarget.releaseCapture(),
a._capturedTarget=null)},triggerEvent:function(b,c,d,f){if(b){if("function"===typeof Event)var g=new Event(c,{bubbles:d,cancelable:f});else g=document.createEvent("Event"),g.initEvent(c,d,f);if(!g)return!1;a.setData(g,"internal",!0);b.dispatchEvent(g);return!0}},triggerInputEvent:function(b,c,d,f){b&&a.isTextInput(b)&&a.triggerEvent(b,c,d,f)},eventKey:function(a){var b={9:"Tab",13:"Enter",27:"Escape"};return"string"===typeof a.code?a.code:void 0!==a.keyCode&&b.hasOwnProperty(a.keyCode)?b[a.keyCode]:
null},strList:function(a){return a?a.replace(/^\s+|\s+$/g,"").split(/\s+/):[]},hasClass:function(a,c){return c?void 0!==a.classList?a.classList.contains(c):-1!=(" "+a.className.replace(/\s+/g," ")+" ").indexOf(" "+c+" "):!1},addClass:function(b,c){c=a.strList(c);if(void 0!==b.classList)for(var d=0;d<c.length;d+=1)b.classList.add(c[d]);else for(d=0;d<c.length;d+=1)a.hasClass(b,c[d])||(b.className+=(b.className?" ":"")+c[d])},removeClass:function(b,c){c=a.strList(c);if(void 0!==b.classList)for(var d=
0;d<c.length;d+=1)b.classList.remove(c[d]);else for(d=0;d<c.length;d+=1)b.className=b.className.replace(new RegExp("^\\s*"+c[d]+"\\s*|\\s*"+c[d]+"\\s*$|\\s+"+c[d]+"(\\s+)","g"),"$1")},getCompStyle:function(a){return(a=window.getComputedStyle?window.getComputedStyle(a):a.currentStyle)?a:{}},setStyle:function(b,c,d,f){d=d?"important":"";var g=null,h;for(h in c)if(c.hasOwnProperty(h)){var k=null;null===c[h]?(g||(g=a.getData(b,"origStyle")),g&&g.hasOwnProperty(h)&&(k=g[h])):(f&&(g||(g=a.getData(b,"origStyle",
{})),g.hasOwnProperty(h)||(g[h]=b.style[h])),k=c[h]);null!==k&&b.style.setProperty(h,k,d)}},linearGradient:function(){var a=function(){for(var a=["","-webkit-","-moz-","-o-","-ms-"],b=document.createElement("div"),f=0;f<a.length;f+=1){var g=a[f]+"linear-gradient";b.style.background=g+"(to right, rgba(0,0,0,0), rgba(0,0,0,0))";if(b.style.background)return g}return"linear-gradient"}();return function(){return a+"("+Array.prototype.join.call(arguments,", ")+")"}}(),setBorderRadius:function(b,c){a.setStyle(b,
{"border-radius":c||"0"})},setBoxShadow:function(b,c){a.setStyle(b,{"box-shadow":c||"none"})},getElementPos:function(b,c){var d=b.getBoundingClientRect();b=d.left;d=d.top;c||(c=a.getViewPos(),b+=c[0],d+=c[1]);return[b,d]},getElementSize:function(a){return[a.offsetWidth,a.offsetHeight]},getAbsPointerPos:function(a){var b=0,d=0;"undefined"!==typeof a.changedTouches&&a.changedTouches.length?(b=a.changedTouches[0].clientX,d=a.changedTouches[0].clientY):"number"===typeof a.clientX&&(b=a.clientX,d=a.clientY);
return{x:b,y:d}},getRelPointerPos:function(a){var b=(a.target||a.srcElement).getBoundingClientRect(),d=0,f=0;"undefined"!==typeof a.changedTouches&&a.changedTouches.length?(d=a.changedTouches[0].clientX,f=a.changedTouches[0].clientY):"number"===typeof a.clientX&&(d=a.clientX,f=a.clientY);return{x:d-b.left,y:f-b.top}},getViewPos:function(){var a=document.documentElement;return[(window.pageXOffset||a.scrollLeft)-(a.clientLeft||0),(window.pageYOffset||a.scrollTop)-(a.clientTop||0)]},getViewSize:function(){var a=
document.documentElement;return[window.innerWidth||a.clientWidth,window.innerHeight||a.clientHeight]},RGB_HSV:function(a,c,d){a/=255;c/=255;d/=255;var b=Math.min(Math.min(a,c),d),g=Math.max(Math.max(a,c),d),h=g-b;if(0===h)return[null,0,100*g];a=a===b?3+(d-c)/h:c===b?5+(a-d)/h:1+(c-a)/h;return[60*(6===a?0:a),h/g*100,100*g]},HSV_RGB:function(a,c,d){d=d/100*255;if(null===a)return[d,d,d];a/=60;c/=100;var b=Math.floor(a),g=d*(1-c);a=d*(1-c*(b%2?a-b:1-(a-b)));switch(b){case 6:case 0:return[d,a,g];case 1:return[a,
d,g];case 2:return[g,d,a];case 3:return[g,a,d];case 4:return[a,g,d];case 5:return[d,g,a]}},parseColorString:function(a){var b={rgba:null,format:null},d;if(d=a.match(/^\W*([0-9A-F]{3}([0-9A-F]{3})?)\W*$/i))return b.format="hex",b.rgba=6===d[1].length?[parseInt(d[1].substr(0,2),16),parseInt(d[1].substr(2,2),16),parseInt(d[1].substr(4,2),16),null]:[parseInt(d[1].charAt(0)+d[1].charAt(0),16),parseInt(d[1].charAt(1)+d[1].charAt(1),16),parseInt(d[1].charAt(2)+d[1].charAt(2),16),null],b;if(d=a.match(/^\W*rgba?\(([^)]*)\)\W*$/i)){a=
d[1].split(",");d=/^\s*(\d+|\d*\.\d+|\d+\.\d*)\s*$/;var f,g,h,k;if(3<=a.length&&(f=a[0].match(d))&&(g=a[1].match(d))&&(h=a[2].match(d)))return b.format="rgb",b.rgba=[parseFloat(f[1])||0,parseFloat(g[1])||0,parseFloat(h[1])||0,null],4<=a.length&&(k=a[3].match(d))&&(b.format="rgba",b.rgba[3]=parseFloat(k[1])||0),b}return!1},scaleCanvasForHighDPR:function(a){var b=window.devicePixelRatio||1;a.width*=b;a.height*=b;a.getContext("2d").scale(b,b)},genColorPreviewCanvas:function(b,c,d,f){var g=Math.round(a.pub.previewSeparator.length),
h=a.pub.chessboardSize,k=a.pub.chessboardColor1,l=a.pub.chessboardColor2;d=d?d:2*h;var n=2*h,m=a.createEl("canvas"),p=m.getContext("2d");m.width=d;m.height=n;f&&a.scaleCanvasForHighDPR(m);p.fillStyle=k;p.fillRect(0,0,d,n);p.fillStyle=l;for(f=0;f<d;f+=2*h)p.fillRect(f,0,h,h),p.fillRect(f+h,h,h,h);b&&(p.fillStyle=b,p.fillRect(0,0,d,n));b=null;switch(c){case "left":b=0;p.clearRect(0,0,g/2,n);break;case "right":b=d-g,p.clearRect(d-g/2,0,g/2,n)}if(null!==b)for(p.lineWidth=1,c=0;c<a.pub.previewSeparator.length;c+=
1)p.beginPath(),p.strokeStyle=a.pub.previewSeparator[c],p.moveTo(.5+b+c,0),p.lineTo(.5+b+c,n),p.stroke();return{canvas:m,width:d,height:n}},genColorPreviewGradient:function(b,c,d){return a.linearGradient.apply(this,c&&d?["to "+{left:"right",right:"left"}[c],b+" 0%",b+" "+d+"px","rgba(0,0,0,0) "+(d+1)+"px","rgba(0,0,0,0) 100%"]:["to right",b+" 0%",b+" 100%"])},redrawPosition:function(){if(a.picker&&a.picker.owner){var b=a.picker.owner;if(b.fixed){var c=a.getElementPos(b.targetElement,!0);var d=[0,
0]}else c=a.getElementPos(b.targetElement),d=a.getViewPos();var f=a.getElementSize(b.targetElement),g=a.getViewSize(),h=a.getPickerOuterDims(b);switch(b.position.toLowerCase()){case "left":var k=1;var l=0;var n=-1;break;case "right":k=1;l=0;n=1;break;case "top":k=0;l=1;n=-1;break;default:k=0,n=l=1}var m=(f[l]+h[l])/2;d=b.smartPosition?[-d[k]+c[k]+h[k]>g[k]?-d[k]+c[k]+f[k]/2>g[k]/2&&0<=c[k]+f[k]-h[k]?c[k]+f[k]-h[k]:c[k]:c[k],-d[l]+c[l]+f[l]+h[l]-m+m*n>g[l]?-d[l]+c[l]+f[l]/2>g[l]/2&&0<=c[l]+f[l]-m-
m*n?c[l]+f[l]-m-m*n:c[l]+f[l]-m+m*n:0<=c[l]+f[l]-m+m*n?c[l]+f[l]-m+m*n:c[l]+f[l]-m-m*n]:[c[k],c[l]+f[l]-m+m*n];a._drawPosition(b,d[k],d[l],b.fixed?"fixed":"absolute",(d[0]+h[0]>c[0]||d[0]<c[0]+f[0])&&d[1]+h[1]<c[1]+f[1])}},_drawPosition:function(b,c,d,f,g){g=g?0:b.shadowBlur;a.picker.wrap.style.position=f;a.picker.wrap.style.left=c+"px";a.picker.wrap.style.top=d+"px";a.setBoxShadow(a.picker.boxS,b.shadow?new a.BoxShadow(0,g,b.shadowBlur,0,b.shadowColor):null)},getPickerDims:function(b){var c=[2*b.controlBorderWidth+
2*b.padding+b.width,2*b.controlBorderWidth+2*b.padding+b.height],d=2*b.controlBorderWidth+2*a.getControlPadding(b)+b.sliderSize;a.getSliderChannel(b)&&(c[0]+=d);b.hasAlphaChannel()&&(c[0]+=d);b.closeButton&&(c[1]+=2*b.controlBorderWidth+b.padding+b.buttonHeight);return c},getPickerOuterDims:function(b){var c=a.getPickerDims(b);return[c[0]+2*b.borderWidth,c[1]+2*b.borderWidth]},getControlPadding:function(a){return Math.max(a.padding/2,2*a.pointerBorderWidth+a.pointerThickness-a.controlBorderWidth)},
getPadYChannel:function(a){switch(a.mode.charAt(1).toLowerCase()){case "v":return"v"}return"s"},getSliderChannel:function(a){if(2<a.mode.length)switch(a.mode.charAt(2).toLowerCase()){case "s":return"s";case "v":return"v"}return null},onDocumentMouseDown:function(b){var c=b.target||b.srcElement;if(c.jscolor&&c.jscolor instanceof a.pub)c.jscolor.showOnClick&&!c.disabled&&c.jscolor.show();else if(a.getData(c,"gui")){if(a.getData(c,"control"))a.onControlPointerStart(b,c,a.getData(c,"control"),"mouse")}else a.picker&&
a.picker.owner&&a.picker.owner.hide()},onDocumentKeyUp:function(b){-1!==["Tab","Escape"].indexOf(a.eventKey(b))&&a.picker&&a.picker.owner&&a.picker.owner.hide()},onWindowResize:function(b){a.redrawPosition()},onParentScroll:function(b){a.picker&&a.picker.owner&&a.picker.owner.hide()},onPickerTouchStart:function(b){var c=b.target||b.srcElement;if(a.getData(c,"control"))a.onControlPointerStart(b,c,a.getData(c,"control"),"touch")},triggerCallback:function(a,c){if(a[c]){var b=null;if("string"===typeof a[c])try{b=
new Function(a[c])}catch(f){console.error(f)}else b=a[c];b&&b.call(a)}},triggerGlobal:function(b){for(var c=a.getInstances(),d=0;d<c.length;d+=1)c[d].trigger(b)},_pointerMoveEvent:{mouse:"mousemove",touch:"touchmove"},_pointerEndEvent:{mouse:"mouseup",touch:"touchend"},_pointerOrigin:null,_capturedTarget:null,onControlPointerStart:function(b,c,d,f){var g=a.getData(c,"instance");a.preventDefault(b);a.captureTarget(c);var h=function(g,h){a.attachGroupEvent("drag",g,a._pointerMoveEvent[f],a.onDocumentPointerMove(b,
c,d,f,h));a.attachGroupEvent("drag",g,a._pointerEndEvent[f],a.onDocumentPointerEnd(b,c,d,f))};h(document,[0,0]);if(window.parent&&window.frameElement){var k=window.frameElement.getBoundingClientRect();h(window.parent.window.document,[-k.left,-k.top])}h=a.getAbsPointerPos(b);k=a.getRelPointerPos(b);a._pointerOrigin={x:h.x-k.x,y:h.y-k.y};switch(d){case "pad":"v"===a.getSliderChannel(g)&&0===g.channels.v&&g.fromHSVA(null,null,100,null);a.setPad(g,b,0,0);break;case "sld":a.setSld(g,b,0);break;case "asld":a.setASld(g,
b,0)}g.trigger("input")},onDocumentPointerMove:function(b,c,d,f,g){return function(b){var f=a.getData(c,"instance");switch(d){case "pad":a.setPad(f,b,g[0],g[1]);break;case "sld":a.setSld(f,b,g[1]);break;case "asld":a.setASld(f,b,g[1])}f.trigger("input")}},onDocumentPointerEnd:function(b,c,d,f){return function(b){b=a.getData(c,"instance");a.detachGroupEvents("drag");a.releaseTarget();b.trigger("input");b.trigger("change")}},setPad:function(b,c,d,f){c=a.getAbsPointerPos(c);d=360/(b.width-1)*(d+c.x-
a._pointerOrigin.x-b.padding-b.controlBorderWidth);f=100-100/(b.height-1)*(f+c.y-a._pointerOrigin.y-b.padding-b.controlBorderWidth);switch(a.getPadYChannel(b)){case "s":b.fromHSVA(d,f,null,null);break;case "v":b.fromHSVA(d,null,f,null)}},setSld:function(b,c,d){c=a.getAbsPointerPos(c);d=100-100/(b.height-1)*(d+c.y-a._pointerOrigin.y-b.padding-b.controlBorderWidth);switch(a.getSliderChannel(b)){case "s":b.fromHSVA(null,d,null,null);break;case "v":b.fromHSVA(null,null,d,null)}},setASld:function(b,c,
d){c=a.getAbsPointerPos(c);d=1-1/(b.height-1)*(d+c.y-a._pointerOrigin.y-b.padding-b.controlBorderWidth);1>d&&"any"===b.format.toLowerCase()&&"rgba"!==b.getFormat()&&(b._currentFormat="rgba");b.fromHSVA(null,null,null,d)},createPalette:function(){var b={elm:null,draw:null},c=a.createEl("canvas"),d=c.getContext("2d");b.elm=c;b.draw=function(a,b,h){c.width=a;c.height=b;d.clearRect(0,0,c.width,c.height);a=d.createLinearGradient(0,0,c.width,0);a.addColorStop(0,"#F00");a.addColorStop(1/6,"#FF0");a.addColorStop(2/
6,"#0F0");a.addColorStop(.5,"#0FF");a.addColorStop(4/6,"#00F");a.addColorStop(5/6,"#F0F");a.addColorStop(1,"#F00");d.fillStyle=a;d.fillRect(0,0,c.width,c.height);a=d.createLinearGradient(0,0,0,c.height);switch(h.toLowerCase()){case "s":a.addColorStop(0,"rgba(255,255,255,0)");a.addColorStop(1,"rgba(255,255,255,1)");break;case "v":a.addColorStop(0,"rgba(0,0,0,0)"),a.addColorStop(1,"rgba(0,0,0,1)")}d.fillStyle=a;d.fillRect(0,0,c.width,c.height)};return b},createSliderGradient:function(){var b={elm:null,
draw:null},c=a.createEl("canvas"),d=c.getContext("2d");b.elm=c;b.draw=function(a,b,h,k){c.width=a;c.height=b;d.clearRect(0,0,c.width,c.height);a=d.createLinearGradient(0,0,0,c.height);a.addColorStop(0,h);a.addColorStop(1,k);d.fillStyle=a;d.fillRect(0,0,c.width,c.height)};return b},createASliderGradient:function(){var b={elm:null,draw:null},c=a.createEl("canvas"),d=c.getContext("2d");b.elm=c;b.draw=function(b,g,h){c.width=b;c.height=g;d.clearRect(0,0,c.width,c.height);b=c.width/2;g=a.pub.chessboardColor2;
d.fillStyle=a.pub.chessboardColor1;d.fillRect(0,0,c.width,c.height);for(var f=0;f<c.height;f+=2*b)d.fillStyle=g,d.fillRect(0,f,b,b),d.fillRect(b,f+b,b,b);b=d.createLinearGradient(0,0,0,c.height);b.addColorStop(0,h);b.addColorStop(1,"rgba(0,0,0,0)");d.fillStyle=b;d.fillRect(0,0,c.width,c.height)};return b},BoxShadow:function(){var a=function(a,b,f,g,h,k){this.hShadow=a;this.vShadow=b;this.blur=f;this.spread=g;this.color=h;this.inset=!!k};a.prototype.toString=function(){var a=[Math.round(this.hShadow)+
"px",Math.round(this.vShadow)+"px",Math.round(this.blur)+"px",Math.round(this.spread)+"px",this.color];this.inset&&a.push("inset");return a.join(" ")};return a}(),flags:{leaveValue:1,leaveAlpha:2,leavePreview:4},enumOpts:{format:["auto","any","hex","rgb","rgba"],previewPosition:["left","right"],mode:["hsv","hvs","hs","hv"],position:["left","right","top","bottom"],alphaChannel:["auto",!0,!1]},deprecatedOpts:{styleElement:"previewElement",onFineChange:"onInput",overwriteImportant:"forceStyle",closable:"closeButton",
insetWidth:"controlBorderWidth",insetColor:"controlBorderColor",refine:null},docsRef:" See https://jscolor.com/docs/",pub:function(b,c){function d(b,c){if("string"!==typeof b)throw Error("Invalid value for option name: "+b);if(a.enumOpts.hasOwnProperty(b)&&("string"===typeof c&&(c=c.toLowerCase()),-1===a.enumOpts[b].indexOf(c)))throw Error("Option '"+b+"' has invalid value: "+c);if(a.deprecatedOpts.hasOwnProperty(b)){var r=a.deprecatedOpts[b];if(r)console.warn("Option '%s' is DEPRECATED, using '%s' instead."+
a.docsRef,b,r),b=r;else throw Error("Option '"+b+"' is DEPRECATED");}if(!(b in e))throw Error("Unrecognized configuration option: "+b);e[b]=c;return!0}function f(){e._processParentElementsInDOM();a.picker||(a.picker={owner:null,wrap:a.createEl("div"),box:a.createEl("div"),boxS:a.createEl("div"),boxB:a.createEl("div"),pad:a.createEl("div"),padB:a.createEl("div"),padM:a.createEl("div"),padPal:a.createPalette(),cross:a.createEl("div"),crossBY:a.createEl("div"),crossBX:a.createEl("div"),crossLY:a.createEl("div"),
crossLX:a.createEl("div"),sld:a.createEl("div"),sldB:a.createEl("div"),sldM:a.createEl("div"),sldGrad:a.createSliderGradient(),sldPtrS:a.createEl("div"),sldPtrIB:a.createEl("div"),sldPtrMB:a.createEl("div"),sldPtrOB:a.createEl("div"),asld:a.createEl("div"),asldB:a.createEl("div"),asldM:a.createEl("div"),asldGrad:a.createASliderGradient(),asldPtrS:a.createEl("div"),asldPtrIB:a.createEl("div"),asldPtrMB:a.createEl("div"),asldPtrOB:a.createEl("div"),btn:a.createEl("div"),btnT:a.createEl("span")},a.picker.pad.appendChild(a.picker.padPal.elm),
a.picker.padB.appendChild(a.picker.pad),a.picker.cross.appendChild(a.picker.crossBY),a.picker.cross.appendChild(a.picker.crossBX),a.picker.cross.appendChild(a.picker.crossLY),a.picker.cross.appendChild(a.picker.crossLX),a.picker.padB.appendChild(a.picker.cross),a.picker.box.appendChild(a.picker.padB),a.picker.box.appendChild(a.picker.padM),a.picker.sld.appendChild(a.picker.sldGrad.elm),a.picker.sldB.appendChild(a.picker.sld),a.picker.sldB.appendChild(a.picker.sldPtrOB),a.picker.sldPtrOB.appendChild(a.picker.sldPtrMB),
a.picker.sldPtrMB.appendChild(a.picker.sldPtrIB),a.picker.sldPtrIB.appendChild(a.picker.sldPtrS),a.picker.box.appendChild(a.picker.sldB),a.picker.box.appendChild(a.picker.sldM),a.picker.asld.appendChild(a.picker.asldGrad.elm),a.picker.asldB.appendChild(a.picker.asld),a.picker.asldB.appendChild(a.picker.asldPtrOB),a.picker.asldPtrOB.appendChild(a.picker.asldPtrMB),a.picker.asldPtrMB.appendChild(a.picker.asldPtrIB),a.picker.asldPtrIB.appendChild(a.picker.asldPtrS),a.picker.box.appendChild(a.picker.asldB),
a.picker.box.appendChild(a.picker.asldM),a.picker.btn.appendChild(a.picker.btnT),a.picker.box.appendChild(a.picker.btn),a.picker.boxB.appendChild(a.picker.box),a.picker.wrap.appendChild(a.picker.boxS),a.picker.wrap.appendChild(a.picker.boxB),a.picker.wrap.addEventListener("touchstart",a.onPickerTouchStart,a.isPassiveEventSupported?{passive:!1}:!1));var b=a.picker,c=!!a.getSliderChannel(e),d=e.hasAlphaChannel(),f=a.getPickerDims(e),l=2*e.pointerBorderWidth+e.pointerThickness+2*e.crossSize,m=a.getControlPadding(e),
n=Math.min(e.borderRadius,Math.round(e.padding*Math.PI));b.wrap.className="jscolor-picker-wrap";b.wrap.style.clear="both";b.wrap.style.width=f[0]+2*e.borderWidth+"px";b.wrap.style.height=f[1]+2*e.borderWidth+"px";b.wrap.style.zIndex=e.zIndex;b.box.className="jscolor-picker";b.box.style.width=f[0]+"px";b.box.style.height=f[1]+"px";b.box.style.position="relative";b.boxS.className="jscolor-picker-shadow";b.boxS.style.position="absolute";b.boxS.style.left="0";b.boxS.style.top="0";b.boxS.style.width="100%";
b.boxS.style.height="100%";a.setBorderRadius(b.boxS,n+"px");b.boxB.className="jscolor-picker-border";b.boxB.style.position="relative";b.boxB.style.border=e.borderWidth+"px solid";b.boxB.style.borderColor=e.borderColor;b.boxB.style.background=e.backgroundColor;a.setBorderRadius(b.boxB,n+"px");b.padM.style.background="rgba(255,0,0,.2)";b.sldM.style.background="rgba(0,255,0,.2)";b.asldM.style.background="rgba(0,0,255,.2)";b.padM.style.opacity=b.sldM.style.opacity=b.asldM.style.opacity="0";b.pad.style.position=
"relative";b.pad.style.width=e.width+"px";b.pad.style.height=e.height+"px";b.padPal.draw(e.width,e.height,a.getPadYChannel(e));b.padB.style.position="absolute";b.padB.style.left=e.padding+"px";b.padB.style.top=e.padding+"px";b.padB.style.border=e.controlBorderWidth+"px solid";b.padB.style.borderColor=e.controlBorderColor;b.padM.style.position="absolute";b.padM.style.left="0px";b.padM.style.top="0px";b.padM.style.width=e.padding+2*e.controlBorderWidth+e.width+m+"px";b.padM.style.height=2*e.controlBorderWidth+
2*e.padding+e.height+"px";b.padM.style.cursor="crosshair";a.setData(b.padM,{instance:e,control:"pad"});b.cross.style.position="absolute";b.cross.style.left=b.cross.style.top="0";b.cross.style.width=b.cross.style.height=l+"px";b.crossBY.style.position=b.crossBX.style.position="absolute";b.crossBY.style.background=b.crossBX.style.background=e.pointerBorderColor;b.crossBY.style.width=b.crossBX.style.height=2*e.pointerBorderWidth+e.pointerThickness+"px";b.crossBY.style.height=b.crossBX.style.width=l+
"px";b.crossBY.style.left=b.crossBX.style.top=Math.floor(l/2)-Math.floor(e.pointerThickness/2)-e.pointerBorderWidth+"px";b.crossBY.style.top=b.crossBX.style.left="0";b.crossLY.style.position=b.crossLX.style.position="absolute";b.crossLY.style.background=b.crossLX.style.background=e.pointerColor;b.crossLY.style.height=b.crossLX.style.width=l-2*e.pointerBorderWidth+"px";b.crossLY.style.width=b.crossLX.style.height=e.pointerThickness+"px";b.crossLY.style.left=b.crossLX.style.top=Math.floor(l/2)-Math.floor(e.pointerThickness/
2)+"px";b.crossLY.style.top=b.crossLX.style.left=e.pointerBorderWidth+"px";b.sld.style.overflow="hidden";b.sld.style.width=e.sliderSize+"px";b.sld.style.height=e.height+"px";b.sldGrad.draw(e.sliderSize,e.height,"#000","#000");b.sldB.style.display=c?"block":"none";b.sldB.style.position="absolute";b.sldB.style.left=e.padding+e.width+2*e.controlBorderWidth+2*m+"px";b.sldB.style.top=e.padding+"px";b.sldB.style.border=e.controlBorderWidth+"px solid";b.sldB.style.borderColor=e.controlBorderColor;b.sldM.style.display=
c?"block":"none";b.sldM.style.position="absolute";b.sldM.style.left=e.padding+e.width+2*e.controlBorderWidth+m+"px";b.sldM.style.top="0px";b.sldM.style.width=e.sliderSize+2*m+2*e.controlBorderWidth+(d?0:Math.max(0,e.padding-m))+"px";b.sldM.style.height=2*e.controlBorderWidth+2*e.padding+e.height+"px";b.sldM.style.cursor="default";a.setData(b.sldM,{instance:e,control:"sld"});b.sldPtrIB.style.border=b.sldPtrOB.style.border=e.pointerBorderWidth+"px solid "+e.pointerBorderColor;b.sldPtrOB.style.position=
"absolute";b.sldPtrOB.style.left=-(2*e.pointerBorderWidth+e.pointerThickness)+"px";b.sldPtrOB.style.top="0";b.sldPtrMB.style.border=e.pointerThickness+"px solid "+e.pointerColor;b.sldPtrS.style.width=e.sliderSize+"px";b.sldPtrS.style.height=a.pub.sliderInnerSpace+"px";b.asld.style.overflow="hidden";b.asld.style.width=e.sliderSize+"px";b.asld.style.height=e.height+"px";b.asldGrad.draw(e.sliderSize,e.height,"#000");b.asldB.style.display=d?"block":"none";b.asldB.style.position="absolute";b.asldB.style.left=
e.padding+e.width+2*e.controlBorderWidth+m+(c?e.sliderSize+3*m+2*e.controlBorderWidth:0)+"px";b.asldB.style.top=e.padding+"px";b.asldB.style.border=e.controlBorderWidth+"px solid";b.asldB.style.borderColor=e.controlBorderColor;b.asldM.style.display=d?"block":"none";b.asldM.style.position="absolute";b.asldM.style.left=e.padding+e.width+2*e.controlBorderWidth+m+(c?e.sliderSize+2*m+2*e.controlBorderWidth:0)+"px";b.asldM.style.top="0px";b.asldM.style.width=e.sliderSize+2*m+2*e.controlBorderWidth+Math.max(0,
e.padding-m)+"px";b.asldM.style.height=2*e.controlBorderWidth+2*e.padding+e.height+"px";b.asldM.style.cursor="default";a.setData(b.asldM,{instance:e,control:"asld"});b.asldPtrIB.style.border=b.asldPtrOB.style.border=e.pointerBorderWidth+"px solid "+e.pointerBorderColor;b.asldPtrOB.style.position="absolute";b.asldPtrOB.style.left=-(2*e.pointerBorderWidth+e.pointerThickness)+"px";b.asldPtrOB.style.top="0";b.asldPtrMB.style.border=e.pointerThickness+"px solid "+e.pointerColor;b.asldPtrS.style.width=
e.sliderSize+"px";b.asldPtrS.style.height=a.pub.sliderInnerSpace+"px";b.btn.className="jscolor-btn-close";b.btn.style.display=e.closeButton?"block":"none";b.btn.style.position="absolute";b.btn.style.left=e.padding+"px";b.btn.style.bottom=e.padding+"px";b.btn.style.padding="0 15px";b.btn.style.maxWidth=f[0]-2*e.padding-2*e.controlBorderWidth-30+"px";b.btn.style.overflow="hidden";b.btn.style.height=e.buttonHeight+"px";b.btn.style.whiteSpace="nowrap";b.btn.style.border=e.controlBorderWidth+"px solid";
(function(){var a=e.controlBorderColor.split(/\s+/);b.btn.style.borderColor=2>a.length?a[0]:a[1]+" "+a[0]+" "+a[0]+" "+a[1]})();b.btn.style.color=e.buttonColor;b.btn.style.font="12px sans-serif";b.btn.style.textAlign="center";b.btn.style.cursor="pointer";b.btn.onmousedown=function(){e.hide()};b.btnT.style.lineHeight=e.buttonHeight+"px";b.btnT.innerHTML="";b.btnT.appendChild(document.createTextNode(e.closeText));g();h();k();a.picker.owner&&a.picker.owner!==e&&a.removeClass(a.picker.owner.targetElement,
a.pub.activeClassName);a.picker.owner=e;e.container===document.body?a.redrawPosition():a._drawPosition(e,0,0,"relative",!1);b.wrap.parentNode!==e.container&&e.container.appendChild(b.wrap);a.addClass(e.targetElement,a.pub.activeClassName)}function g(){var b=a.getPadYChannel(e);b=Math.round((1-e.channels[b]/100)*(e.height-1));var c=-Math.floor((2*e.pointerBorderWidth+e.pointerThickness+2*e.crossSize)/2);a.picker.cross.style.left=Math.round(e.channels.h/360*(e.width-1))+c+"px";a.picker.cross.style.top=
b+c+"px";switch(a.getSliderChannel(e)){case "s":c=a.HSV_RGB(e.channels.h,100,e.channels.v);b=a.HSV_RGB(e.channels.h,0,e.channels.v);c="rgb("+Math.round(c[0])+","+Math.round(c[1])+","+Math.round(c[2])+")";a.picker.sldGrad.draw(e.sliderSize,e.height,c,"rgb("+Math.round(b[0])+","+Math.round(b[1])+","+Math.round(b[2])+")");break;case "v":b=a.HSV_RGB(e.channels.h,e.channels.s,100),c="rgb("+Math.round(b[0])+","+Math.round(b[1])+","+Math.round(b[2])+")",a.picker.sldGrad.draw(e.sliderSize,e.height,c,"#000")}a.picker.asldGrad.draw(e.sliderSize,
e.height,e.toHEXString())}function h(){var b=a.getSliderChannel(e);b&&(a.picker.sldPtrOB.style.top=Math.round((1-e.channels[b]/100)*(e.height-1))-(2*e.pointerBorderWidth+e.pointerThickness)-Math.floor(a.pub.sliderInnerSpace/2)+"px");a.picker.asldGrad.draw(e.sliderSize,e.height,e.toHEXString())}function k(){a.picker.asldPtrOB.style.top=Math.round((1-e.channels.a)*(e.height-1))-(2*e.pointerBorderWidth+e.pointerThickness)-Math.floor(a.pub.sliderInnerSpace/2)+"px"}function l(){return a.picker&&a.picker.owner===
e}function n(b){"Enter"===a.eventKey(b)&&(e.valueElement&&e.processValueInput(e.valueElement.value),e.hide())}function m(b){"Enter"===a.eventKey(b)&&(e.alphaElement&&e.processAlphaInput(e.alphaElement.value),e.hide())}function p(b){a.getData(b,"internal")||(b=e.valueElement.value,e.processValueInput(e.valueElement.value),a.triggerCallback(e,"onChange"),e.valueElement.value!==b&&a.triggerInputEvent(e.valueElement,"change",!0,!0))}function x(b){a.getData(b,"internal")||(b=e.alphaElement.value,e.processAlphaInput(e.alphaElement.value),
a.triggerCallback(e,"onChange"),a.triggerInputEvent(e.valueElement,"change",!0,!0),e.alphaElement.value!==b&&a.triggerInputEvent(e.alphaElement,"change",!0,!0))}function y(b){a.getData(b,"internal")||(e.valueElement&&e.fromString(e.valueElement.value,a.flags.leaveValue),a.triggerCallback(e,"onInput"))}function z(b){a.getData(b,"internal")||(e.alphaElement&&e.fromHSVA(null,null,null,parseFloat(e.alphaElement.value),a.flags.leaveAlpha),a.triggerCallback(e,"onInput"),a.triggerInputEvent(e.valueElement,
"input",!0,!0))}var e=this;c||(c={});this.channels={r:255,g:255,b:255,h:0,s:0,v:100,a:1};this.format="rgba";this.previewElement=this.alphaElement=this.valueElement=this.onInput=this.onChange=this.alpha=this.value=void 0;this.previewPosition="left";this.previewSize=32;this.previewPadding=8;this.forceStyle=this.uppercase=this.hash=this.required=!0;this.width=181;this.height=101;this.mode="HSV";this.alphaChannel="auto";this.position="bottom";this.showOnClick=this.smartPosition=!0;this.sliderSize=16;
this.crossSize=8;this.closeButton=!1;this.closeText="Close";this.buttonColor="rgba(0,0,0,1)";this.buttonHeight=18;this.padding=12;this.backgroundColor="rgba(255,255,255,1)";this.borderWidth=1;this.borderColor="rgba(255,255,255,0)";this.borderRadius=8;this.controlBorderWidth=1;this.controlBorderColor="rgba(187,187,187,1)";this.shadow=!1;this.shadowBlur=15;this.shadowColor="rgba(0,0,0,0.2)";this.pointerColor="rgba(76,76,76,1)";this.pointerBorderWidth=1;this.pointerBorderColor="rgba(255,255,255,1)";
this.pointerThickness=2;this.zIndex=5E3;this.container=void 0;this.minS=0;this.maxS=100;this.minV=0;this.maxV=100;this.minA=0;this.maxA=1;if(a.pub.options)for(var q in a.pub.options)if(a.pub.options.hasOwnProperty(q))try{d(q,a.pub.options[q])}catch(r){console.warn(r)}var t=[];c.preset&&("string"===typeof c.preset?t=c.preset.split(/\s+/):Array.isArray(c.preset)?t=c.preset.slice():console.warn("Unrecognized preset value"));-1===t.indexOf("default")&&t.push("default");for(var w=t.length-1;0<=w;--w){var u=
t[w];if(u)if(!a.pub.presets.hasOwnProperty(u))console.warn("Unknown preset: %s",u);else for(q in a.pub.presets[u])if(a.pub.presets[u].hasOwnProperty(q))try{d(q,a.pub.presets[u][q])}catch(r){console.warn(r)}}t=["preset"];for(q in c)if(c.hasOwnProperty(q)&&-1===t.indexOf(q))try{d(q,c[q])}catch(r){console.warn(r)}this.option=function(){if(!arguments.length)throw Error("No option specified");if(1===arguments.length&&"string"===typeof arguments[0]){try{var b=arguments[0];if(a.deprecatedOpts.hasOwnProperty(b)){var c=
a.deprecatedOpts[b];if(c)console.warn("Option '%s' is DEPRECATED, using '%s' instead."+a.docsRef,b,c),b=c;else throw Error("Option '"+b+"' is DEPRECATED");}if(!(b in e))throw Error("Unrecognized configuration option: "+b);return e[b]}catch(v){console.warn(v)}return!1}if(2<=arguments.length&&"string"===typeof arguments[0]){try{if(!d(arguments[0],arguments[1]))return!1}catch(v){return console.warn(v),!1}this.redraw();this.exposeColor();return!0}if(1===arguments.length&&"object"===typeof arguments[0]){b=
arguments[0];c=!0;for(var f in b)if(b.hasOwnProperty(f))try{d(f,b[f])||(c=!1)}catch(v){console.warn(v),c=!1}this.redraw();this.exposeColor();return c}throw Error("Invalid arguments");};this.channel=function(a,b){if("string"!==typeof a)throw Error("Invalid value for channel name: "+a);if(void 0===b)return this.channels.hasOwnProperty(a.toLowerCase())?this.channels[a.toLowerCase()]:(console.warn("Getting unknown channel: "+a),!1);switch(a.toLowerCase()){case "r":a=this.fromRGBA(b,null,null,null);break;
case "g":a=this.fromRGBA(null,b,null,null);break;case "b":a=this.fromRGBA(null,null,b,null);break;case "h":a=this.fromHSVA(b,null,null,null);break;case "s":a=this.fromHSVA(null,b,null,null);break;case "v":a=this.fromHSVA(null,null,b,null);break;case "a":a=this.fromHSVA(null,null,null,b);break;default:return console.warn("Setting unknown channel: "+a),!1}return a?(this.redraw(),!0):!1};this.trigger=function(b){b=a.strList(b);for(var c=0;c<b.length;c+=1){var d=b[c].toLowerCase(),e=null;switch(d){case "input":e=
"onInput";break;case "change":e="onChange"}e&&a.triggerCallback(this,e);a.triggerInputEvent(this.valueElement,d,!0,!0)}};this.fromHSVA=function(b,c,d,e,f){void 0===b&&(b=null);void 0===c&&(c=null);void 0===d&&(d=null);void 0===e&&(e=null);if(null!==b){if(isNaN(b))return!1;this.channels.h=Math.max(0,Math.min(360,b))}if(null!==c){if(isNaN(c))return!1;this.channels.s=Math.max(0,Math.min(100,this.maxS,c),this.minS)}if(null!==d){if(isNaN(d))return!1;this.channels.v=Math.max(0,Math.min(100,this.maxV,d),
this.minV)}if(null!==e){if(isNaN(e))return!1;this.channels.a=this.hasAlphaChannel()?Math.max(0,Math.min(1,this.maxA,e),this.minA):1}b=a.HSV_RGB(this.channels.h,this.channels.s,this.channels.v);this.channels.r=b[0];this.channels.g=b[1];this.channels.b=b[2];this.exposeColor(f);return!0};this.fromRGBA=function(b,c,d,e,f){void 0===b&&(b=null);void 0===c&&(c=null);void 0===d&&(d=null);void 0===e&&(e=null);if(null!==b){if(isNaN(b))return!1;b=Math.max(0,Math.min(255,b))}if(null!==c){if(isNaN(c))return!1;
c=Math.max(0,Math.min(255,c))}if(null!==d){if(isNaN(d))return!1;d=Math.max(0,Math.min(255,d))}if(null!==e){if(isNaN(e))return!1;this.channels.a=this.hasAlphaChannel()?Math.max(0,Math.min(1,this.maxA,e),this.minA):1}b=a.RGB_HSV(null===b?this.channels.r:b,null===c?this.channels.g:c,null===d?this.channels.b:d);null!==b[0]&&(this.channels.h=Math.max(0,Math.min(360,b[0])));0!==b[2]&&(this.channels.s=Math.max(0,this.minS,Math.min(100,this.maxS,b[1])));this.channels.v=Math.max(0,this.minV,Math.min(100,this.maxV,
b[2]));b=a.HSV_RGB(this.channels.h,this.channels.s,this.channels.v);this.channels.r=b[0];this.channels.g=b[1];this.channels.b=b[2];this.exposeColor(f);return!0};this.fromHSV=function(b,c,d,e){console.warn("fromHSV() method is DEPRECATED. Using fromHSVA() instead."+a.docsRef);return this.fromHSVA(b,c,d,null,e)};this.fromRGB=function(b,c,d,e){console.warn("fromRGB() method is DEPRECATED. Using fromRGBA() instead."+a.docsRef);return this.fromRGBA(b,c,d,null,e)};this.fromString=function(b,c){if(!this.required&&
""===b.trim())return this.setPreviewElementBg(null),this.setValueElementValue(""),!0;b=a.parseColorString(b);if(!b)return!1;"any"===this.format.toLowerCase()&&(this._currentFormat=b.format,"rgba"!==this.getFormat()&&(b.rgba[3]=1),this.redraw());this.fromRGBA(b.rgba[0],b.rgba[1],b.rgba[2],b.rgba[3],c);return!0};this.toString=function(a){void 0===a&&(a=this.getFormat());switch(a.toLowerCase()){case "hex":return this.toHEXString();case "rgb":return this.toRGBString();case "rgba":return this.toRGBAString()}return!1};
this.toHEXString=function(){return"#"+(("0"+Math.round(this.channels.r).toString(16)).substr(-2)+("0"+Math.round(this.channels.g).toString(16)).substr(-2)+("0"+Math.round(this.channels.b).toString(16)).substr(-2)).toUpperCase()};this.toRGBString=function(){return"rgb("+Math.round(this.channels.r)+","+Math.round(this.channels.g)+","+Math.round(this.channels.b)+")"};this.toRGBAString=function(){return"rgba("+Math.round(this.channels.r)+","+Math.round(this.channels.g)+","+Math.round(this.channels.b)+
","+Math.round(100*this.channels.a)/100+")"};this.toGrayscale=function(){return.213*this.channels.r+.715*this.channels.g+.072*this.channels.b};this.toCanvas=function(){return a.genColorPreviewCanvas(this.toRGBAString()).canvas};this.toDataURL=function(){return this.toCanvas().toDataURL()};this.toBackground=function(){return a.pub.background(this.toRGBAString())};this.isLight=function(){return 127.5<this.toGrayscale()};this.hide=function(){l()&&(a.removeClass(e.targetElement,a.pub.activeClassName),
a.picker.wrap.parentNode.removeChild(a.picker.wrap),delete a.picker.owner)};this.show=function(){f()};this.redraw=function(){l()&&f()};this.getFormat=function(){return this._currentFormat};this.hasAlphaChannel=function(){return"auto"===this.alphaChannel?"any"===this.format.toLowerCase()||"rgba"===this.getFormat()||void 0!==this.alpha||void 0!==this.alphaElement:this.alphaChannel};this.processValueInput=function(a){this.fromString(a)||this.exposeColor()};this.processAlphaInput=function(a){this.fromHSVA(null,
null,null,parseFloat(a))||this.exposeColor()};this.exposeColor=function(b){if(!(b&a.flags.leaveValue)&&this.valueElement){var c=this.toString();"hex"===this.getFormat()&&(this.uppercase||(c=c.toLowerCase()),this.hash||(c=c.replace(/^#/,"")));this.setValueElementValue(c)}b&a.flags.leaveAlpha||!this.alphaElement||(c=Math.round(100*this.channels.a)/100,this.setAlphaElementValue(c));b&a.flags.leavePreview||!this.previewElement||(a.isTextInput(this.previewElement)||a.isButton(this.previewElement)&&a.isButtonEmpty(this.previewElement),
this.setPreviewElementBg(this.toRGBAString()));l()&&(g(),h(),k())};this.setPreviewElementBg=function(b){if(this.previewElement){var c=null,d=null;if(a.isTextInput(this.previewElement)||a.isButton(this.previewElement)&&!a.isButtonEmpty(this.previewElement))c=this.previewPosition,d=this.previewSize;var e=[];b?(e.push({image:a.genColorPreviewGradient(b,c,d?d-a.pub.previewSeparator.length:null),position:"left top",size:"auto",repeat:c?"repeat-y":"repeat",origin:"padding-box"}),b=a.genColorPreviewCanvas("rgba(0,0,0,0)",
c?{left:"right",right:"left"}[c]:null,d,!0),e.push({image:"url('"+b.canvas.toDataURL()+"')",position:(c||"left")+" top",size:b.width+"px "+b.height+"px",repeat:c?"repeat-y":"repeat",origin:"padding-box"})):e.push({image:"none",position:"left top",size:"auto",repeat:"no-repeat",origin:"padding-box"});b=[];d=[];for(var f=[],g=[],h=[],k=0;k<e.length;k+=1)b.push(e[k].image),d.push(e[k].position),f.push(e[k].size),g.push(e[k].repeat),h.push(e[k].origin);e={"background-image":b.join(", "),"background-position":d.join(", "),
"background-size":f.join(", "),"background-repeat":g.join(", "),"background-origin":h.join(", ")};a.setStyle(this.previewElement,e,this.forceStyle);e={left:null,right:null};c&&(e[c]=this.previewSize+this.previewPadding+"px");e={"padding-left":e.left,"padding-right":e.right};a.setStyle(this.previewElement,e,this.forceStyle,!0)}};this.setValueElementValue=function(b){this.valueElement&&("input"===a.nodeName(this.valueElement)?this.valueElement.value=b:this.valueElement.innerHTML=b)};this.setAlphaElementValue=
function(b){this.alphaElement&&("input"===a.nodeName(this.alphaElement)?this.alphaElement.value=b:this.alphaElement.innerHTML=b)};this._processParentElementsInDOM=function(){if(!this._linkedElementsProcessed){this._linkedElementsProcessed=!0;var b=this.targetElement;do{var c=a.getCompStyle(b);c.position&&"fixed"===c.position.toLowerCase()&&(this.fixed=!0);b===this.targetElement||a.getData(b,"hasScrollListener")||(b.addEventListener("scroll",a.onParentScroll,!1),a.setData(b,"hasScrollListener",!0))}while((b=
b.parentNode)&&"body"!==a.nodeName(b))}};this.container=void 0===this.container?document.body:a.node(this.container);if(!this.container)throw Error("Cannot instantiate color picker without a container element");this.targetElement=a.node(b);if(!this.targetElement){if("string"===typeof b&&/^[a-zA-Z][\w:.-]*$/.test(b))throw Error("If '"+b+"' is supposed to be an ID, please use '#"+b+"' or any valid CSS selector.");throw Error("Cannot instantiate color picker without a target element");}if(this.targetElement.jscolor&&
this.targetElement.jscolor instanceof a.pub)throw Error("Color picker already installed on this element");this.targetElement.jscolor=this;a.addClass(this.targetElement,a.pub.className);a.instances.push(this);a.isButton(this.targetElement)&&("button"!==this.targetElement.type.toLowerCase()&&(this.targetElement.type="button"),a.isButtonEmpty(this.targetElement)&&(a.removeChildren(this.targetElement),this.targetElement.appendChild(document.createTextNode("\u00a0")),b=a.getCompStyle(this.targetElement),
(parseFloat(b["min-width"])||0)<this.previewSize&&a.setStyle(this.targetElement,{"min-width":this.previewSize+"px"},this.forceStyle)));void 0===this.valueElement?a.isTextInput(this.targetElement)&&(this.valueElement=this.targetElement):null!==this.valueElement&&(this.valueElement=a.node(this.valueElement));this.alphaElement&&(this.alphaElement=a.node(this.alphaElement));void 0===this.previewElement?this.previewElement=this.targetElement:null!==this.previewElement&&(this.previewElement=a.node(this.previewElement));
this.valueElement&&a.isTextInput(this.valueElement)&&(b=this.valueElement.oninput,this.valueElement.oninput=null,this.valueElement.addEventListener("keydown",n,!1),this.valueElement.addEventListener("change",p,!1),this.valueElement.addEventListener("input",y,!1),b&&this.valueElement.addEventListener("input",b,!1),this.valueElement.setAttribute("autocomplete","off"),this.valueElement.setAttribute("autocorrect","off"),this.valueElement.setAttribute("autocapitalize","off"),this.valueElement.setAttribute("spellcheck",
!1));this.alphaElement&&a.isTextInput(this.alphaElement)&&(this.alphaElement.addEventListener("keydown",m,!1),this.alphaElement.addEventListener("change",x,!1),this.alphaElement.addEventListener("input",z,!1),this.alphaElement.setAttribute("autocomplete","off"),this.alphaElement.setAttribute("autocorrect","off"),this.alphaElement.setAttribute("autocapitalize","off"),this.alphaElement.setAttribute("spellcheck",!1));b="FFFFFF";void 0!==this.value?b=this.value:this.valueElement&&void 0!==this.valueElement.value&&
(b=this.valueElement.value);c=void 0;void 0!==this.alpha?c=""+this.alpha:this.alphaElement&&void 0!==this.alphaElement.value&&(c=this.alphaElement.value);this._currentFormat=null;-1<["auto","any"].indexOf(this.format.toLowerCase())?this._currentFormat=(q=a.parseColorString(b))?q.format:"hex":this._currentFormat=this.format.toLowerCase();this.processValueInput(b);void 0!==c&&this.processAlphaInput(c)}};a.pub.className="jscolor";a.pub.activeClassName="jscolor-active";a.pub.looseJSON=!0;a.pub.presets=
{};a.pub.presets["default"]={};a.pub.presets.light={backgroundColor:"rgba(255,255,255,1)",controlBorderColor:"rgba(187,187,187,1)",buttonColor:"rgba(0,0,0,1)"};a.pub.presets.dark={backgroundColor:"rgba(51,51,51,1)",controlBorderColor:"rgba(153,153,153,1)",buttonColor:"rgba(240,240,240,1)"};a.pub.presets.small={width:101,height:101,padding:10,sliderSize:14};a.pub.presets.medium={width:181,height:101,padding:12,sliderSize:16};a.pub.presets.large={width:271,height:151,padding:12,sliderSize:24};a.pub.presets.thin=
{borderWidth:1,controlBorderWidth:1,pointerBorderWidth:1};a.pub.presets.thick={borderWidth:2,controlBorderWidth:2,pointerBorderWidth:2};a.pub.sliderInnerSpace=3;a.pub.chessboardSize=8;a.pub.chessboardColor1="#666666";a.pub.chessboardColor2="#999999";a.pub.previewSeparator=["rgba(255,255,255,.65)","rgba(128,128,128,.65)"];a.pub.install=function(b){var c=!0;try{a.installBySelector("[data-jscolor]",b)}catch(d){c=!1,console.warn(d)}if(a.pub.lookupClass)try{a.installBySelector("input."+a.pub.lookupClass+
", button."+a.pub.lookupClass,b)}catch(d){}return c};a.pub.trigger=function(b){a.initialized?a.triggerGlobal(b):a.triggerQueue.push(b)};a.pub.hide=function(){a.picker&&a.picker.owner&&a.picker.owner.hide()};a.pub.chessboard=function(b){b||(b="rgba(0,0,0,0)");return a.genColorPreviewCanvas(b).canvas.toDataURL()};a.pub.background=function(b){var c=[];c.push(a.genColorPreviewGradient(b));b=a.genColorPreviewCanvas();c.push(["url('"+b.canvas.toDataURL()+"')","left top repeat"].join(" "));return c.join(", ")};
a.pub.options={};a.pub.lookupClass="jscolor";a.pub.init=function(){console.warn("jscolor.init() is DEPRECATED. Using jscolor.install() instead."+a.docsRef);return a.pub.install()};a.pub.installByClassName=function(){console.error('jscolor.installByClassName() is DEPRECATED. Use data-jscolor="" attribute instead of a class name.'+a.docsRef);return!1};a.register();return a.pub}(),window.JSColor=window.jscolor);